DATASET: 'NuScenesDataset_OCC_EXT'
DATA_PATH: '/home/stanliu/code/OpenPCDet/extracted_mot_data'

VERSION: 'v1.0-trainval'
MAX_SWEEPS: 15
PRED_VELOCITY: False
SET_NAN_VELOCITY_TO_ZEROS: False
FILTER_MIN_POINTS_IN_GT: 1
TRAIN_RATIO: 0.85
SPLIT_VAL: True
num_workers: 16
OCC: True
DATA_SPLIT: {
    'train': train,
    'test': val
}

INFO_PATH: {
    'train': [nuscenes_infos_occ_15sweeps_test.pkl],
    'test': [nuscenes_infos_occ_15sweeps_test.pkl],
}

MOTION_INFO_PATH: {
    'train': [nuscenes_infos_occ_15sweeps_test_temp.pkl],
    'test': [nuscenes_infos_occ_15sweeps_test_temp.pkl],
}

REF_PCL_PATH: 'nuscenes_occ_database_15sweeps_withvelo'
AUGMENT_DATA: True
POINT_CLOUD_RANGE: [-7.2, -7.2, -2.5, 7.2, 7.2, 2.5]

BALANCED_RESAMPLING: False

DATA_AUGMENTOR:
    DISABLE_AUG_LIST: ['placeholder']
    AUG_CONFIG_LIST:
        # - NAME: gt_sampling
        #   DB_INFO_PATH:
        #       - nuscenes_dbinfos_10sweeps_withvelo.pkl
        #   PREPARE: {
        #      filter_by_min_points: [
        #          'car:2','truck:2', 'construction_vehicle:2', 'bus:2', 'trailer:2',
        #          'barrier:2', 'motorcycle:2', 'bicycle:2', 'pedestrian:2', 'traffic_cone:2'
        #      ],
        #   }

        #   SAMPLE_GROUPS: [
        #       'car:2','truck:3', 'construction_vehicle:7', 'bus:4', 'trailer:6',
        #       'barrier:2', 'motorcycle:6', 'bicycle:6', 'pedestrian:2', 'traffic_cone:2'
        #   ]

        #   NUM_POINT_FEATURES: 5
        #   DATABASE_WITH_FAKELIDAR: False
        #   REMOVE_EXTRA_WIDTH: [0.0, 0.0, 0.0]
        #   LIMIT_WHOLE_SCENE: True

        - NAME: random_world_flip
          ALONG_AXIS_LIST: ['x', 'y']

        - NAME: random_world_rotation
          WORLD_ROT_ANGLE: [-0.78539816, 0.78539816]

        - NAME: random_world_scaling
          WORLD_SCALE_RANGE: [0.9, 1.1]
        
        - NAME: random_world_translation
          NOISE_TRANSLATE_STD: [0.2, 0.2, 0.2]


POINT_FEATURE_ENCODING: {
    encoding_type: absolute_coordinates_encoding,
    used_feature_list: ['x', 'y', 'z', 'intensity', 'timestamp'],
    src_feature_list: ['x', 'y', 'z', 'intensity', 'timestamp'],
}


DATA_PROCESSOR:
    - NAME: mask_points_and_boxes_outside_range
      REMOVE_OUTSIDE_BOXES: True

    - NAME: shuffle_points
      SHUFFLE_ENABLED: {
        'train': False,
        'test': False
      }

    - NAME: transform_points_to_voxels
      VOXEL_SIZE: [0.05, 0.05, 0.1]
      MAX_POINTS_PER_VOXEL: 15
      MAX_NUMBER_OF_VOXELS: {
        'train': 60000,
        'test': 60000
      }
CLASS_NAMES: ['car','truck',  'bus', 'trailer']

DATA_CONFIG:
    _BASE_CONFIG_: /home/stanliu/code/OpenPCDet/data_extraction/nuscenes_dataset_occ.yaml
    POINT_CLOUD_RANGE: [-7.2, -7.2, -2.5, 7.2, 7.2, 2.5]
    VAL_BATCH_SIZE: 30
    VERSION: 'v1.0-mini'
    DATA_AUGMENTOR:
        DISABLE_AUG_LIST: ['placeholder']
        AUG_CONFIG_LIST:
            # - NAME: gt_sampling
            #   DB_INFO_PATH:
            #     - nuscenes_dbinfos_10sweeps_withvelo.pkl
            #   PREPARE: {
            #     filter_by_min_points: [
            #         'car:5','truck:5', 'construction_vehicle:5', 'bus:5', 'trailer:5',
            #         'barrier:5', 'motorcycle:5', 'bicycle:5', 'pedestrian:5', 'traffic_cone:5'
            #     ],
            #   }

            #   SAMPLE_GROUPS: [
            #     'car:2','truck:3', 'construction_vehicle:7', 'bus:4', 'trailer:6',
            #     'barrier:2', 'motorcycle:6', 'bicycle:6', 'pedestrian:2', 'traffic_cone:2'
            #   ]

            #   NUM_POINT_FEATURES: 5
            #   DATABASE_WITH_FAKELIDAR: False
            #   REMOVE_EXTRA_WIDTH: [0.0, 0.0, 0.0]
            #   LIMIT_WHOLE_SCENE: True

            - NAME: random_world_flip
              ALONG_AXIS_LIST: ['x', 'y']

            - NAME: random_world_rotation
              WORLD_ROT_ANGLE: [-0.78539816, 0.78539816]

            - NAME: random_world_scaling
              WORLD_SCALE_RANGE: [0.9, 1.1]
            
            - NAME: random_world_translation
              NOISE_TRANSLATE_STD: [0.2, 0.2, 0.2]


    DATA_PROCESSOR:
        - NAME: mask_points_and_boxes_outside_range
          REMOVE_OUTSIDE_BOXES: True

        - NAME: shuffle_points
          SHUFFLE_ENABLED: {
            'train': False,
            'test': False
          }

        - NAME: transform_points_to_voxels
          VOXEL_SIZE: [0.05, 0.05, 0.1]
          MAX_POINTS_PER_VOXEL: 10
          MAX_NUMBER_OF_VOXELS: {
            'train': 120000,
            'test': 160000
          }


MODEL:
    NAME: CenterPoint
    CONTRAST: True
    FEAT_EXTRACTION: True
    VFE:
        NAME: MeanVFE

    BACKBONE_3D:
        NAME: VoxelResBackBone8x

    MAP_TO_BEV:
        NAME: HeightCompression
        NUM_BEV_FEATURES: 256

    BACKBONE_2D:
        NAME: BaseBEVBackbone

        LAYER_NUMS: [5, 5]
        LAYER_STRIDES: [1, 2]
        NUM_FILTERS: [128, 256]
        UPSAMPLE_STRIDES: [1, 2]
        NUM_UPSAMPLE_FILTERS: [256, 256]

    DENSE_HEAD:
        NAME: CenterHead
        CLASS_AGNOSTIC: False

        CLASS_NAMES_EACH_HEAD: [
            ['car'], 
            ['truck', 'construction_vehicle'],
            ['bus', 'trailer']
        ]

        SHARED_CONV_CHANNEL: 64
        USE_BIAS_BEFORE_NORM: True
        NUM_HM_CONV: 2
        SEPARATE_HEAD_CFG:
            HEAD_ORDER: ['center', 'center_z', 'dim', 'rot']
            HEAD_DICT: {
                'center': {'out_channels': 2, 'num_conv': 2},
                'center_z': {'out_channels': 1, 'num_conv': 2},
                'dim': {'out_channels': 3, 'num_conv': 2},
                'rot': {'out_channels': 2, 'num_conv': 2}
            }

        TARGET_ASSIGNER_CONFIG:
            FEATURE_MAP_STRIDE: 8
            NUM_MAX_OBJS: 500
            GAUSSIAN_OVERLAP: 0.1
            MIN_RADIUS: 2

        LOSS_CONFIG:
            LOSS_WEIGHTS: {
                'cls_weight': 1.0,
                'loc_weight': 0.25,
                'code_weights': [0.5, 0.5, 0.5, 1.0, 1.0, 1.0, 0.2, 0.2]
            }

        POST_PROCESSING:
            SCORE_THRESH: 0.1
            POST_CENTER_LIMIT_RANGE: [-7.2, -7.2, -5.0, 7.2, 7.2, 5.0]
            MAX_OBJ_PER_SAMPLE: 500
            NMS_CONFIG:
                NMS_TYPE: nms_gpu
                NMS_THRESH: 0.2
                NMS_PRE_MAXSIZE: 1000
                NMS_POST_MAXSIZE: 83
    CONTRAST_HEAD:
        NAME: ContrastHead
        CLASS_AGNOSTIC: False

        SHARED_CONV_CHANNEL: 64
        num_conv: 2
        out_channels: 32
        contrast_metric: cosine
        code_weights: [10.0,10.0,10.0]
        

    POST_PROCESSING:
        RECALL_THRESH_LIST: [0.3, 0.5, 0.7]

        EVAL_METRIC: kitti



OPTIMIZATION:
    BATCH_SIZE_PER_GPU: 18
    NUM_EPOCHS: 20

    OPTIMIZER: adam_onecycle
    LR: 0.001
    WEIGHT_DECAY: 0.01
    MOMENTUM: 0.9

    MOMS: [0.95, 0.85]
    PCT_START: 0.4
    DIV_FACTOR: 10
    DECAY_STEP_LIST: [35, 45]
    LR_DECAY: 0.1
    LR_CLIP: 0.0000001

    LR_WARMUP: False
    WARMUP_EPOCH: 1

    GRAD_NORM_CLIP: 10

batch_size: 30
num_workers: 12

motion_ckpt_path: 'motion_associator/adj_time_motion_associator.tar'
map_ckpt_path: 'motion_associator/short_time_map_associator.tar'
motion_model_cfg:
  # Encoder parameters
  encoder_type: 'match_encoder'
  encoder_args:
    fuse_map: False
    target_feat_size: 8
    target_emb_size: 16
    past_enc_size: 24
    node_feat_size: 8
    node_emb_size: 16
    node_enc_size: 48
    future_enc_size: 64
    lane_enc_size: 64
    




  # Aggregator parameters
  aggregator_type: 'match_agg'
  aggregator_args:
    agg_method: 'none'
    node_enc_size: 64
    att_hidden_size: 32

  # Decoder parameters
  decoder_type: 'match_decoder'
  decoder_args:
    fuse_map: False
    hist_enc_size: 24
    future_enc_size: 64
    node_enc_size: 64
    input_size: 88

map_model_cfg:
  # Encoder parameters
  encoder_type: 'match_encoder'
  encoder_args:
    fuse_map: True
    target_feat_size: 8
    target_emb_size: 16
    past_enc_size: 24
    node_feat_size: 8
    node_emb_size: 16
    node_enc_size: 48
    future_enc_size: 64
    lane_enc_size: 64
    


  # Aggregator parameters
  aggregator_type: 'match_agg'
  aggregator_args:
    agg_method: 'fully_connected'
    node_enc_size: 64
    att_hidden_size: 32
    num_gat_layers: 2

  # Decoder parameters
  decoder_type: 'match_decoder'
  decoder_args:
    fuse_map: True
    hist_enc_size: 24
    future_enc_size: 64
    node_enc_size: 64
    input_size: 88
