# Dataset and dataloader parameters
dataset: 'nuScenes'
version: 'v1.0-trainval'
# version: 'v1.0-mini'
agent_setting: 'single_agent'
input_representation: 'graphs'

train_set_args: &ds_args
  split: 'train'
  # split: 'mini_train'
  t_h: 2
  t_f: 6
  map_extent: [ -50, 50, -20, 100 ]
  polyline_resolution: 1
  polyline_length: 20
  traversal_horizon: 15
  random_flips: False
  use_home: False
  use_raster: False

val_set_args:
  <<: *ds_args
  split: 'train_val'
  # split: 'mini_val'
  random_flips: False
  use_home: False
  use_raster: False

test_set_args:
  <<: *ds_args
  split: 'val'
  random_flips: False
  use_home: False
  use_raster: False

batch_size: 96
num_workers: 8
use_teacher_force: False
nrow: 6
pretrain: True
pretrain_epcs: 8
visualize_start_epoch: 7

focal_args:
  map_extent: [ -100, 100, -100, 100 ]
  gauss_blur: True
  resolution: 0.5
  window_size: 13
  horizon: 1
  type: 'sum'
  reduce_map: False
  normalize: False
  only_last: True

# Encoder parameters
encoder_type: 'pgp_encoder_occ'
encoder_args:
  map_aggregation: True
  motion_enc_type: 'ugru'
  target_agent_feat_size: 4
  target_agent_emb_size: 24
  target_agent_enc_size: 32
  node_feat_size: 6
  node_emb_size: 16
  node_enc_size: 48
  nbr_feat_size: 5
  nbr_emb_size: 16
  nbr_enc_size: 32
  num_gat_layers: 2
  fuse_map_with_tgt: False
  # map_size: 36
  # tn_head_num: 2
  




# Aggregator parameters
aggregator_type: 'attn_occ'
aggregator_args:
  method: 'concat'
  pre_train: False
  time_emb_size: 12
  target_emb_size: 32
  query_enc_size: 48
  attn_size: 36
  map_size: 36

# Decoder parameters
decoder_type: 'mlp_occ'
decoder_args:
  add_attention: True
  time_emb_size: 48
  node_enc_size: 48
  refinement: True
  sep_motion_emb: False
  motion_emb_size: 18
  traj_emb_size: 48
  use_gru: True

# Optimizer parameters
optim_args:
  lr: 0.001
  scheduler_step: 10
  scheduler_gamma: 0.5


# losses: ['ade', 'yaw_loss','ade', 'yaw_loss']
losses: ['ade', 'yaw_loss', 'ade', 'yaw_loss', 'ade', 'yaw_loss']
loss_weights: [1, 0.5, 1.5, 0.5, 2.5, 1.0]
loss_args:
  - target: 'initial'
  - target: 'initial'
  - target: 'refine'
  - target: 'refine'
  - target: 'endpoints'
  - target: 'endpoints'



tr_metrics: ['ade','yaw_loss' ,'miss_rate','ade','yaw_loss']
tr_metric_args:
  - target: 'initial'
  - target: 'initial'
  - dist_thresh: 2.0
    target: 'initial'
  - target: 'endpoints'
  - target: 'endpoints'
  # - target: 'refine'
  # - target: 'refine'

val_metrics: [ 'ade', 'yaw_loss','ade', 'yaw_loss','ade', 'yaw_loss']
val_metric_args:
  - target: 'initial'
  - target: 'initial'
  - target: 'endpoints'
  - target: 'endpoints'
  - target: 'refine'
  - target: 'refine'


log_freq: 100