dataset: 'nuScenes'
version: 'v1.0-trainval'
agent_setting: 'single_agent'
input_representation: 'vector'

train_set_args:
  split: 'train'
  t_h: 2
  t_f: 6
  use_home: True
  use_raster: True
  polyline_resolution: 1
  polyline_length: 20
  traversal_horizon: 15
  map_extent: [-61, 61, -22, 100]
  img_size: [488,488]
  generate_heatmap: False

val_set_args:
  split: 'train_val'
  t_h: 2
  t_f: 6
  use_home: True
  use_raster: True
  polyline_resolution: 1
  polyline_length: 20
  traversal_horizon: 15
  map_extent: [-61, 61, -22, 100]
  img_size: [488,488]
  generate_heatmap: False

test_set_args:
  split: 'val'
  t_h: 2
  t_f: 6
  use_home: True
  use_raster: True
  polyline_resolution: 1
  polyline_length: 20
  traversal_horizon: 15
  map_extent: [-61, 61, -22, 100]
  img_size: [488,488]
  generate_heatmap: False

batch_size: 16
num_workers: 8
verbosity: True
