dataset: 'nuScenes'
version: 'v1.0-trainval'
agent_setting: 'single_agent'
input_representation: 'raster'

train_set_args:
  split: 'train'
  t_h: 2
  t_f: 6
  map_extent: [-61, 61, -22, 100]
  img_size: [488,488]
  generate_heatmap: False

val_set_args:
  split: 'train_val'
  t_h: 2
  t_f: 6
  map_extent: [-61, 61, -22, 100]
  img_size: [488,488]
  generate_heatmap: False

test_set_args:
  split: 'val'
  t_h: 2
  t_f: 6
  map_extent: [-61, 61, -22, 100]
  img_size: [488,488]
  generate_heatmap: False

batch_size: 32
num_workers: 4
verbosity: True

