# Dataset and dataloader parameters
dataset: 'nuScenes'
version: 'v1.0-trainval'
agent_setting: 'single_agent'
input_representation: 'raster'

train_set_args: &ds_args
  split: 'train'
  t_h: 2
  t_f: 6
  map_extent: [-61, 61, -22, 100]
  img_size: [488,488]
  random_flips: True

val_set_args:
  <<: *ds_args
  split: 'train_val'
  random_flips: False

test_set_args:
  <<: *ds_args
  split: 'val'
  random_flips: False

batch_size: 6
num_workers: 8





encoder_type: 'raster_encoder'
encoder_args:
  backbone: 'resnet18'
  input_channels: 6
  use_positional_encoding: True
  target_agent_feat_size: 3
  target_agent_enc_size: 32
  


# Aggregator parameters
aggregator_type: 'ram'
aggregator_args:
  pre_train: False
  backbone: 'resnet18'
  target_agent_enc_size: 32
  map_extent: [-61, 61, -22, 100]
  context_enc_size: 512
  img_size: [488,488]
  resolution: 1
  emb_size: 128
  num_heads: 2
  convolute: True
  conv_kernel_ratio: 0.15
  out_channels: 64

# aggregator_type: 'home_agg'
# aggregator_args:
#   pre_train: False
#   backbone: 'resnet18'
#   target_agent_enc_size: 32
#   map_extent: [-61, 61, -22, 100]
#   context_enc_size: 512
#   img_size: [488,488]
#   resolution: 1
#   emb_size: 128
#   num_heads: 1
#   convolute: True
#   conv_kernel_ratio: 0.15
#   out_channels: 32


# Decoder parameters
decoder_type: 'ram_decoder'
decoder_args:
  agg_type: 'ram'
  conc_range: 18
  map_extent: [-61, 61, -22, 100]
  resolution: 1
  agg_channel: 64 ##should be same with 'out_channels' in 'aggregator_args', if the aggregator is 2DSampler
  decoder_depth: 3
  heatmap_channel: 12

# decoder_type: 'home'
# decoder_args:
#   agg_type: 'home_agg'
#   conc_range: 18
#   map_extent: [-61, 61, -22, 100]
#   resolution: 1
#   agg_channel: 32 ##should be same with 'out_channels' in 'aggregator_args', if the aggregator is 2DSampler
#   decoder_depth: 2
#   heatmap_channel: 12



# Optimizer parameters
optim_args:
  lr: 0.002
  scheduler_step: 10
  scheduler_gamma: 0.5


losses: ['focal_loss','drivable_loss']
loss_weights: [1,0.01]
loss_args:
  - gauss_blur: True
    map_extent: [-61, 61, -22, 100]
    resolution: 1
    window_size: 7
    horizon: 12
    type: 'sum'
  - type: 'sum'


tr_metrics: ['focal_loss','drivable_loss']
tr_metric_args:
  - gauss_blur: True
    map_extent: [-61, 61, -22, 100]
    resolution: 1
    window_size: 7
    horizon: 12
    type: 'sum'
  - type: 'sum'

val_metrics: ['focal_loss','drivable_loss']
val_metric_args:
  - gauss_blur: True
    map_extent: [-61, 61, -22, 100]
    resolution: 1
    window_size: 7
    horizon: 12
    type: 'sum'
  - type: 'sum'


log_freq: 100