# Dataset and dataloader parameters
dataset: 'nuScenes'
version: 'v1.0-trainval'
agent_setting: 'single_agent'
input_representation: 'raster'

train_set_args: &ds_args
  split: 'train'
  t_h: 2
  t_f: 6
  map_extent: [-61, 61, -22, 100]
  img_size: [488,488]
  random_flips: True

val_set_args:
  <<: *ds_args
  split: 'train_val'
  random_flips: False

test_set_args:
  <<: *ds_args
  split: 'val'
  random_flips: False

batch_size: 32
num_workers: 4





encoder_type: 'raster_encoder'
encoder_args:
  backbone: 'resnet18'
  input_channels: 6
  use_positional_encoding: True
  target_agent_feat_size: 3
  target_agent_enc_size: 32
  


# Aggregator parameters
aggregator_type: 'home_agg'
aggregator_args:
  pre_train: False
  backbone: 'resnet18'
  target_agent_enc_size: 32
  map_extent: [-61, 61, -22, 100]
  context_enc_size: 512
  img_size: [488,488]
  resolution: 1
  emb_size: 128
  num_heads: 1
  convolute: True
  conv_kernel_ratio: 0.15
  out_channels: 64


# Decoder parameters
decoder_type: 'ram'
decoder_args:
  agg_type: 'home_agg'
  conc_range: 18
  resolution: 1
  agg_channel: 64 ##should be same with 'out_channels' in 'aggregator_args'
  decoder_depth: 4



# Optimizer parameters
optim_args:
  lr: 0.001
  scheduler_step: 10
  scheduler_gamma: 0.5


losses: ['min_ade_k', 'pi_bc']
loss_weights: [1, 0.5]
loss_args:
  - k: 10
  - dummy: 0


tr_metrics: ['min_ade_k', 'miss_rate_k', 'pi_bc']
tr_metric_args:
  - k: 10
  - k: 10
    dist_thresh: 2
  - dummy: 0

val_metrics: ['min_ade_k','min_ade_k', 'miss_rate_k', 'miss_rate_k', 'pi_bc']
val_metric_args:
  - k: 5
  - k: 10
  - k: 5
    dist_thresh: 2
  - k: 10
    dist_thresh: 2
  - dummy: 0


log_freq: 100