# Dataset and dataloader parameters
dataset: 'nuScenes'
version: 'v1.0-mini'
agent_setting: 'single_agent'
input_representation: 'vector'


train_set_args: &ds_args
  split: 'mini_train'
  t_h: 2
  t_f: 6
  use_raster: True
  use_home: True
  polyline_resolution: 1
  polyline_length: 20
  traversal_horizon: 15
  map_extent: [-61, 61, -22, 100]
  img_size: [488,488]
  random_flips: False

val_set_args:
  <<: *ds_args
  split: 'mini_val'
  use_raster: True
  use_home: True
  polyline_resolution: 1
  polyline_length: 20
  traversal_horizon: 15
  map_extent: [-61, 61, -22, 100]
  img_size: [488,488]
  random_flips: False

test_set_args:
  <<: *ds_args
  split: 'mini_val'
  use_raster: True
  use_home: True
  polyline_resolution: 1
  polyline_length: 20
  traversal_horizon: 15
  map_extent: [-61, 61, -22, 100]
  img_size: [488,488]
  random_flips: False

batch_size: 1
num_workers: 8
nrow: 4





encoder_type: 'home_encoder'
encoder_args:
  backbone: 'home'
  hidden_dim: 32
  num_heads: 4
  input_channels: 6
  traj_forecaster: True
  emb_size: 128
  use_positional_encoding: False
  target_agent_feat_size: 3
  target_agent_enc_size: 24
  


# Aggregator parameters
aggregator_type: 'home_agg'
aggregator_args:
  pre_train: False
  agg_type: 'attention'
  backbone: 'resnet34'
  target_agent_enc_size: 128
  map_extent: [-61, 61, -22, 100]
  context_enc_size: 512
  img_size: [488,488]
  resolution: 0.25
  emb_size: 128


# aggregator_type: 'home_agg'
# aggregator_args:
#   pre_train: False
#   backbone: 'resnet18'
#   target_agent_enc_size: 32
#   map_extent: [-61, 61, -22, 100]
#   context_enc_size: 512
#   img_size: [488,488]
#   resolution: 1
#   emb_size: 128
#   num_heads: 1
#   convolute: True
#   conv_kernel_ratio: 0.15
#   out_channels: 32


# Decoder parameters
decoder_type: 'home'
decoder_args:
  agg_type: 'home_agg'
  map_extent: [-61, 61, -22, 100]
  resolution: 0.25
  # agg_channel: 32 ##should be same with 'out_channels' in 'aggregator_args', if the aggregator is 2DSampler
  # decoder_depth: 2
  heatmap_channel: 12
  output_traj: True
  num_target: 20
  num_heads: 4
  emb_size: 64
  # time_emb_size: 31
  sample_radius: 4
  target_agent_enc_size: 24
  emb_size: 128
  diff_emb: 8
  map_dim: 512
  pretrain_mlp: False
  use_positional_encoding: False
# decoder_type: 'home'
# decoder_args:
#   agg_type: 'home_agg'
#   conc_range: 18
#   map_extent: [-61, 61, -22, 100]
#   resolution: 1
#   agg_channel: 32 ##should be same with 'out_channels' in 'aggregator_args', if the aggregator is 2DSampler
#   decoder_depth: 2
#   heatmap_channel: 12



# Optimizer parameters
optim_args:
  lr: 0.001
  scheduler_step: 3
  scheduler_gamma: 0.5

# Full parameters
losses: ['focal_loss','min_ade_k','drivable_loss']
loss_weights: [1.0,0.25,500.0]
loss_args:
  - gauss_blur: True
    map_extent: [-61, 61, -22, 100]
    resolution: 0.25
    window_size: 13
    horizon: 12
    type: 'sum'
    reduce_map: False
    normalize: False
    only_last: True
  - k: 1
  - type: 'mean'



tr_metrics: ['focal_loss','min_ade_k', 'min_ade_loss','drivable_loss','min_fde_k']
tr_metric_args:
  - gauss_blur: True
    map_extent: [-61, 61, -22, 100]
    resolution: 0.25
    window_size: 13
    horizon: 12
    type: 'sum'
    reduce_map: False
    normalize: False
    only_last: True
  - k: 10
  - dummy: 0
  - type: 'mean'
  - k: 10


val_metrics: ['focal_loss','min_ade_k', 'miss_rate_k','min_ade_k', 'miss_rate_k' , 'min_fde_k']
val_metric_args:
  - gauss_blur: True
    map_extent: [-61, 61, -22, 100]
    resolution: 0.25
    window_size: 13
    horizon: 12
    type: 'sum'
    reduce_map: False
    normalize: False
    only_last: True
  - k: 10
  - k: 10
    dist_thresh: 2
  - k: 5
  - k: 5
    dist_thresh: 2
  - k: 10


# Pretraining MLP decoders
# losses: ['min_ade_k','min_fde_k']
# loss_weights: [1.0,0.2]
# loss_args:
#   - k: 1
#   - k: 1



# tr_metrics: ['min_fde_k','min_ade_k']
# tr_metric_args:
#   - k: 1
#   - k: 1
#   - k: 1



# val_metrics: ['min_ade_k','min_ade_k']
# val_metric_args:
#   - k: 1
#   - k: 1



log_freq: 100
